spring:
  application:
    name: workout
  datasource:
    url: ${WORKOUT_DB_URL:jdbc:mysql://mysql5.sqlpub.com:3310/inv_doc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${WORKOUT_DB_USER:user_lipp}
    password: ${WORKOUT_DB_PASSWORD:pgGSlfNr1pSJbcq1}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
  flyway:
    enabled: true
  jackson:
    time-zone: Asia/Shanghai

server:
  port: 8080

workout:
  jwt:
    secret: ${WORKOUT_JWT_SECRET:ZK++GivMTbpopIqjpEeQNjikcFBnSzu0iy+mYXPDlzkCQ4f7IW/99AcSIixVpXyC}
    expire-days: 7
